apiVersion: v1
kind: Service
metadata:
  name:  vegetable-service
  namespace: bhagwat-ns
spec:
  type: LoadBalancer
  selector:
    app: vegetable
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
